CREATE DATABASE animales;
use animales;
CREATE TABLE felinos(id int NOT NULL AUTO_INCREMENT ,ww YEAR(25) NOT NULL ,doblexd DOUBLE NOT NULL ,mes SMALLINT  ,PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;